[package]
name = "nbbs-credit-retirement"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
soroban-sdk = "26.0.1"
nbbs-shared = { path = "../shared" }
nbbs-coupon-engine = { path = "../coupon-engine" }

[dev-dependencies]
soroban-sdk = { version = "26.0.1", features = ["testutils"] }
nbbs-bond-issuer = { path = "../bond-issuer", features = ["testutils"] }
nbbs-coupon-engine = { path = "../coupon-engine", features = ["testutils"] }
nbbs-oracle-consumer = { path = "../oracle-consumer", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
